### PR TITLE
Add support for using treq.

### PR DESCRIPTION
**Pull request by Lukasa**
In case you wanted vindication of your approach, here's a quick example of using treq instead of using aiohttp. It's basically exactly as many lines of code as the aiohttp version.

To test it out, `pip install twisted treq` and then:

```python
from twisted.internet import reactor, defer, task
from gidgethub.treq import GitHubAPI


MY_TOKEN = "INSERT_TOKEN_HERE"
USER_AGENT = "INSERT_USERNAME_HERE"


def main(reactor, *args):
    gh = GitHubAPI(USER_AGENT, oauth_token=MY_TOKEN)
    d = defer.ensureDeferred(gh.getitem("/repos/python-hyper/hyper-h2/labels/Easy"))
    d.addCallback(print)
    return d

task.react(main)
```

`ensureDeferred` is the only bit of interesting stuff required here: then, everything just drops into place. This is a really good example of more complex sans-io library structure here Brett, great job! :sparkles:

### CODE REVIEW

**Comment by Lukasa** [comment]
Of course, *testing* this will be a bit harder. I'll probably need to use trial for that, which is a bit of a tricky thing to do with your current testing model.

**Comment by Lukasa** [comment]
Hey look, test coverage!

**Comment by brettcannon** [comment]
Do you have any suggestions on how to tweak the testing to make it easier? I'm open to changing it (especially since I am going to have to revert 6b3dc032f1fcdf0fbf23dfb061f11588798c1e7e to get test coverage back).

**Comment by brettcannon** [comment]
And while I'm thinking about it, is using the "twisted" name for the extra over-extending? I.e. will there be other Twisted-based approaches people might want instead? (I don't know Twisted to know if this is a silly question or not.)

**Comment by brettcannon** [comment]
And last question: did you want to write the docs or would you rather I do it? (It honestly doesn't bother me if you would rather punt it over to me as I will just copy your opening bit to this PR 😁 ).

**Comment by brettcannon** [comment]
Turns out I don't need to revert the test change, but I'm still happy to discuss ways to improve testing.

**Comment by Lukasa** [comment]
The honest answer is *probably*, so let's change the extra name to treq. I can write you some docs. :smile:

**Comment by brettcannon** [comment]
Thanks for this, @Lukasa ! I'll try to push out a 1.1.0 release today or tomorrow with this change in it.

**Pull request merged**
