### PR TITLE
Graphql

### PR DESCRIPTION
**Pull request by warsaw**
Here are a couple of things I've found useful as I'm using this framework for some of my own apps.

* Support wildcard event dispatch
* Add the [v4 GraphQL](https://developer.github.com/v4/) endpoint
* Add a `gidgethub.sansio.format_query()` function which uses [PEP 292](https://www.python.org/dev/peps/pep-0292/) style templates for formulate GraphQL queries.  Why PEP 292 instead of `.format()` or f-strings?  Yeah, well have fun escaping your GraphQL braces! :)

Here's an example GraphQL query call:

```
@router.register('pull_request_review')
@router.register('pull_request_review_comment')
async def check_comments_resolved(event, gh, *args, **kwargs):
    """Add a status block when there are unresolved review comments"""
    # Get the review comment thread for the PR being edited.
    event_data = ObjectifyJSON(event.data)
    pr_number = event_data.pull_request.number
    query = format_query("""
{
  repository(owner:"xxx", name:"yyy") {
    issueOrPullRequest(number:$pr_number) {
      ... on PullRequest {
        id
        reviewThreads(last:50) {
          nodes {
            id,
            isResolved
          }
        }
        commits(last: 1) {
          nodes {
            commit {
              oid
            }
          }
        }
      }
    }
  }
}
""", dict(pr_number=pr_number))
    json = await gh.post(sansio.V4_DOMAIN, data=dict(query=query), oauth_token=gh.oauth_token)

### CODE REVIEW

**Comment by brettcannon** [comment]
I don't think I'm ready to bring on GraphQL stuff until I have some time to evaluate other GraphQL client libraries to see how good of a job they are doing. Once that's done then I would be willing to discuss how to handle GraphQL appropriately.

As for the wildcard, is `"*"` the best solution or would making `event_type` be `Optional[str]` make more sense? Not sure which one is better.

**Comment by warsaw** [comment]
The Python GraphQL libraries I found were pretty darn simple.  What I found interesting is that the libraries don't really help much in writing the GraphQL queries.  For that, it's just as easy to write them inline inside a triple quoted string.  The other interesting thing is that I had to choose `string.Template` as the interpolation language because of the huge number of braces used in the query.  It just makes no sense to have to quote them.

I totally understand your hesitation.  I'll be very interested in seeing what you find.

As for the choice of `*` for wildcard; I saw that somewhere in the GH docs to mean "all your events are belong to us".  Sorry, don't remember where I read that.  (OTOH, this is Python, so `*` works equally as well as `None` or some constant.)

**Comment by brettcannon** [comment]
I don't expect any library to help write queries, just to help make the call and consume the results of the call (the playground is rather handy for figuring out what query you do want in the end, so I don't see call composition as a critical thing as much as not having to figure out what goes where in the REST call and pulling apart the response if possible).

And you read about `*` at https://developer.github.com/webhooks/#wildcard-event. :) So if you want to do a new PR just for wildcards with appropriate docs and tests we would be up for taking it.

**Comment by warsaw** [comment]
TBH, the most useful thing from this PR is `V4_DOMAIN` since that's the end point for all GH GraphQL queries.  But OTOH, it's a one-liner so easy to lift.

The only other thing I'd say that useful is to turn the the resulting JSON into an object for dot-attribute access.  That's pure convenience though, so I'm not even sure if you want to make a statement on that.

It's all so simple, it makes the GraphQL API really appealing.  I can also see why although there are other GraphQL libraries on PyPI, it almost doesn't seem worth pulling in another dependency.  GidgetHub is still really useful because REST is harder and there is not yet functional parity between GH REST and GraphQL.

**Comment by warsaw** [comment]
I'll think about a separate PR for the wildcarding.

**Comment by brettcannon** [comment]
@warsaw I actually want typing support for the resulting data since you can infer that from the query and inspecting the schema of the service.

**Pull request closed without merging**
