### PR TITLE
Update noxfile, test against Python 3.9

### PR DESCRIPTION
**Pull request by Mariatta**

### CODE REVIEW

**Review by brettcannon — APPROVED** [review]

**Comment by Mariatta** [comment]
I'm addressing the CI/lint jobs, but no sure about the failing tests in 3.9.
Any initial thoughts, are these problem with Python 3.9, or with aiohttp? 😕

**Comment by Mariatta** [comment]
Depends on #145, we should merge that one first.

**Comment by brettcannon** [comment]
The failure seems to be a change in coverage under Python 3.9. Probably looking at what coverage.py reports will make it more obvious (although why codecov thinks everything is fine I don't know; maybe it's rounding up?).

**Comment by Mariatta** [comment]
The test failed due to a change in pyjwt library. In PyJWT 2.0.0, the `jwt.encode()` returns a string instead of bytestring. Basically they dropped compatibility with Python 2 :)

Do we want to require gidgethub to only work with PyJWT > 2.0.0 from now on? I think currently the PyJWT version is not pinned. This might require a major version bump.

**Comment by Mariatta** [comment]
This is PyJWT's changelog for v2.0.0: https://github.com/jpadilla/pyjwt/blob/master/CHANGELOG.md#v200

**Comment by brettcannon** [comment]
I'm fine with requiring a newer version of JWT. As for a version bump, if we have to change our code to be compatible then I view it as a bugfix if it doesn't require client code to change. If people can't use it because they require an older version of JWT then they just won't get the update (and we won't support a branch for older JWT anyway, so no need to worry about that either).

**Comment by Mariatta** [comment]
There's a warning about :unclosed transport" but I'm not familiar with any of it 😕 

```
/opt/hostedtoolcache/Python/3.9.1/x64/lib/python3.9/asyncio/selector_events.py:704: ResourceWarning: unclosed transport <_SelectorSocketTransport fd=15>
  _warn(f"unclosed transport {self!r}", ResourceWarning, source=self)
ResourceWarning: Enable tracemalloc to get the object allocation traceback
/opt/hostedtoolcache/Python/3.9.1/x64/lib/python3.9/asyncio/selector_events.py:704: ResourceWarning: unclosed transport <_SelectorSocketTransport fd=16>
  _warn(f"unclosed transport {self!r}", ResourceWarning, source=self)
ResourceWarning: Enable tracemalloc to get the object allocation traceback

=============================== warnings summary ===============================
tests/test_apps.py::TestGitHubAppUtils::test_get_jwt
  /opt/hostedtoolcache/Python/3.9.1/x64/lib/python3.9/asyncio/selector_events.py:704: ResourceWarning: unclosed transport <_SelectorSocketTransport fd=15>
    _warn(f"unclosed transport {self!r}", ResourceWarning, source=self)

tests/test_apps.py::TestGitHubAppUtils::test_get_jwt
  /home/runner/work/gidgethub/gidgethub/.nox/tests-3-9/lib/python3.9/site-packages/cryptography/hazmat/backends/openssl/x509.py:419: ResourceWarning: unclosed <socket.socket fd=16, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('10.1.0.4', 33996), raddr=('140.82.112.5', 443)>
    def signature_algorithm_oid(self):

tests/test_apps.py::TestGitHubAppUtils::test_get_jwt
  /opt/hostedtoolcache/Python/3.9.1/x64/lib/python3.9/asyncio/selector_events.py:704: ResourceWarning: unclosed transport <_SelectorSocketTransport fd=16>
    _warn(f"unclosed transport {self!r}", ResourceWarning, source=self)

-- Docs: https://docs.pytest.org/en/stable/warnings.html
```

**Comment by Mariatta** [comment]
For the most recent check run, there are also warnings on test_get in test_aiohttp.py, so perhaps it's not just the PyJWT module.
```
=============================== warnings summary ===============================
tests/test_aiohttp.py::test_get
  /opt/hostedtoolcache/Python/3.9.1/x64/lib/python3.9/traceback.py:359: ResourceWarning: unclosed <socket.socket fd=15, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('10.1.0.4', 35112), raddr=('140.82.114.6', 443)>
    result.append(FrameSummary(

tests/test_aiohttp.py::test_get
  /opt/hostedtoolcache/Python/3.9.1/x64/lib/python3.9/asyncio/selector_events.py:704: ResourceWarning: unclosed transport <_SelectorSocketTransport fd=15>
    _warn(f"unclosed transport {self!r}", ResourceWarning, source=self)
```

**Comment by Mariatta** [comment]
I don't understand why the coverage works differently in Python 3.9. I've tried looking into "fixing" it, but couldn't figure out how. So I added a `# pragma: nocover` to this line https://github.com/brettcannon/gidgethub/pull/142/commits/5fdf5fc565ab566c9dd8e81bc9b63d81c7e15866#diff-fa8ea3270653fcdde75cd4cf2647885665593ed67284eced64abc965f91c8dcdR162

**Review by brettcannon — APPROVED** [review]

**Comment by brettcannon** [comment]
LGTM!

**Pull request merged**
