### PR TITLE
Move to flit

### PR DESCRIPTION
**Pull request by Mariatta**
- remove ``setup.cfg`` and ``setup.py``
- add docstring to ``__init__.py``
- add ``__version__`` to`` __init__.py``
- add ``flit.ini``
- explicitly state in the readme that gidgethub requires Python 3.6

Closes https://github.com/brettcannon/gidgethub/issues/41

### CODE REVIEW

**Comment by Mariatta** [comment]
Hm, I don't know how to fix the broken tests... 😞

**Comment by brettcannon** [comment]
New version of mypy is probably stricter/better at detecting problems than it used to be. Fix is a separate issue.

**Comment by brettcannon** [comment]
As a certain someone asked me to give a tutorial to a certain user's group on packaging 😉 , I'm going to convert this project to flit live as part of it. Because of that I'm going to close this.

**Comment by brettcannon** [comment]
Since we are going to be bumping the version number I think it's acceptable to drop the extras support and just expect people to install their async library that they want.

**Comment by Mariatta** [comment]
Ok I can see about creating the PR again.
Magic of GitHub: I've deleted my branch so I've lost my copy, but the patch still exists [here](https://patch-diff.githubusercontent.com/raw/brettcannon/gidgethub/pull/42.patch) 😃

**Pull request closed without merging**
