### PR TITLE
Use X-Hub-Signature-256 for webhook validation

### PR DESCRIPTION
**Pull request by Vovcharaa**
As github recommends here: https://docs.github.com/en/developers/webhooks-and-events/securing-your-webhooks#validating-payloads-from-github

### CODE REVIEW

**Review by brettcannon — APPROVED** [review]

**Review by Mariatta — APPROVED** [review]
Thanks! I confirmed that GitHub is sending both `x-hub-signature-256` and `x-hub-signature` headers for now.

Not sure about if we need to mention this anywhere in the doc, but perhaps worth mentioning in changelog, that the new header is supported.

**Comment by brettcannon** [comment]
Definitely needs to be mentioned in the changelog in case someone is running some old version of the GH Enterprise where this would make a difference.

**Comment by Mariatta** [comment]
Oh that's a good point, I wasn't thinking about GH Enterprise earlier.

I just checked the docs for GH Enterprise:
v 2.21 and v 2.22, `x-hub-signature` is being sent.
In v 3.0, both `x-hub-signature` and `x-hub-signature-256` are being sent.

I think for now it's better for gidgethub to support both `x-hub-signature-256` and `x-hub-signature`, instead of just `x-hub-signature-256`.

**Review by Mariatta — CHANGES_REQUESTED** [review]
I think we should support both `x-hub-signature-256` and `x-hub-signature` for now.
Perhaps it can first check if `x-hub-signature-256` exists, and fallback to `x-hub-signature`.

Also, please update the changelog.

**Comment by Mariatta** [comment]
Documentation links, for reference:
v3.0 https://docs.github.com/en/enterprise-server@3.0/developers/webhooks-and-events/webhook-events-and-payloads#delivery-headers
v2.22 https://docs.github.com/en/enterprise-server@2.22/developers/webhooks-and-events/webhook-events-and-payloads#delivery-headers
v2.21 https://docs.github.com/en/enterprise-server@2.21/developers/webhooks-and-events/webhook-events-and-payloads

**Review by Mariatta — APPROVED** [review]
Thanks. Sorry for not being able to review in more timely manner.

**Pull request merged**
