### PR TITLE
Start using Sphinx>=4.0

### PR DESCRIPTION
**Pull request by Mariatta**
- Require the minimum Sphinx version to 4.0,
(where PyClassmember was removed)
- Remove customization.py
- use the Sphinx builtin :abstractmethod: and :async: options to document coroutines

Closes https://github.com/brettcannon/gidgethub/issues/143

### CODE REVIEW

**Comment by Mariatta** [comment]
It looks like there's a difference in how different themes are rendering the `:async:` and `:abstractmethod:` options.

In the alabaster theme (local machine), I was able to render those correctly:

Screen Shot 2021-06-15 at 1 56 20 PM

In the readthedocs preview documentation, it looks like none of those are being displayed correctly. Example is the members of `abc.GitHubAPI`

Screen Shot 2021-06-15 at 1 58 06 PM

**Comment by Mariatta** [comment]
Looking at the build log, it looks like the version of sphinx_rtd_theme that got installed on readthedocs side is 0.4.3, and we need something newer. 😕

**Comment by Mariatta** [comment]
Had to create docs_requirements.txt file, but it seems to look fine now.

I wasn't sure about bumping the version of gidgethub itself. Is this just increasing the minor version?

**Review by brettcannon — APPROVED** [review]

**Comment by brettcannon** [comment]
I don't think any version needs to be bumped since it doesn't affect the wheel file.

**Pull request merged**
